#function file
import turtle
a=turtle.Turtle()

def light(distance,color):
    a.penup()
    a.goto(-130,30)
    a.pendown()
    a.color(color)
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-220,80)
    a.pendown()
    a.begin_fill()
    a.left(90)
    for times in range(3):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.right(90)
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
    a.forward(distance*3)
    for times in range(3):
        a.left(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-240,110)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*3)
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    for times in range(3):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.end_fill()

    a.penup()
    a.goto(-250,140)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    for times in range(3):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-210,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-200,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()
    
def dark(distance,color):
    a.color(color)
    a.begin_fill()
    a.penup()
    a.goto(-140,40)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()
    a.begin_fill()
    a.penup()
    a.goto(-150,60)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-160,80)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-140,90)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-130,70)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-210,70)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,100)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-210,110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-190,120)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-170,130)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-240,150)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,150)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-210,160)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-180,180)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-220,180)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-210,190)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-220,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

def lightB(distance,color):
    a.color(color)
    a.penup()
    a.goto(-230,80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-240,90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance*2)
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-250,110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance*3)
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,110)
    a.pendown()
    a.begin_fill()
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,120)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-140,130)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-150,140)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*4)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-100,150)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-110,180)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-130,200)
    a.pendown()
    a.begin_fill()
    for tiems in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-150,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def yellow(distance,color):
    a.color(color)
    a.penup()
    a.goto(-130,130)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

def whitish(distance,color):
    a.color(color)
    a.penup()
    a.goto(-130,140)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-140,140)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-150,170)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*3)
    a.end_fill()

    a.penup()
    a.goto(-150,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,170)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,150)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,130)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

def redish(distance,color):
    a.color(color)
    a.penup()
    a.goto(-120,140)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-130,150)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-140,170)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-140,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def orange(distance,color):
    a.color(color)
    a.penup()
    a.goto(-130,180)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,160)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,130)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.left(90)

def black(distance,color):
    a.color(color)
    a.penup()
    a.goto(-140,30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance*3)
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-140,-10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,-20)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*4)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-110,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-90)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-140,-90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*8)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-50,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-30,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*8)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(50,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-90)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(30,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(50,-60)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-20)
    a.pendown()
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*4)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(20,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(20,30)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*6)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*4)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-100,50)
    a.pendown()
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-160,70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-180,60)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
    a.end_fill()

    a.penup()
    a.goto(-220,70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-240,90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-250,110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*5)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-240,160)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,170)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-220,180)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-190,200)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,190)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,190)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-100,170)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*5)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-110,120)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-120,110)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-120,90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-30,-30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*3)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(0,-30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*3)
        a.left(90)
        a.forward(distance)
    a.end_fill()

def darkR (distance,color):
    a.color(color)
    a.penup()
    a.goto(-90,40)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-110,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-140,20)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-150,30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-160,50)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()
    
    a.penup()
    a.goto(-150,80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-180,70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-220,70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-110,50)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-110)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-30,-110)
    a.pendown()
    a.begin_fill()
    a.forward(distance*3)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(30,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(40,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-60)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-10,10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-40,10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()
    
    a.penup()
    a.goto(-130,-90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-60,-110)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-200,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,200)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-230,200)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-170,200)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

def darkpink (distance,color):
    a.color(color)
    a.penup()
    a.goto(30,-110)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(10,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-60,-110)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance*6)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*5)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-110,-80)
    a.pendown()
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-110,-40)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-120,-10)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-130,0)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-140,20)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-80,40)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-60,50)
    a.pendown()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-50,20)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-50,0)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,20)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,0)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,-40)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(30,10)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(20,-70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-20,-100)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()
    
def medpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(-120,-80)
    a.pendown()
    a.begin_fill()
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*5)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(40,-80)
    for times in range(2):
        a.forward(distance*3)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()

def hotpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(-100,-40)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-50,-20)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(0,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,0)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-90,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-10,-10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(10,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-70,40)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(0,10)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-20,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-10,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def lightishpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(-10,-70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*3)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-60,-60)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-70,-50)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-80,-40)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-90,-30)
    a.pendown()
    a.begin_fill()
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-110,10)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-90,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-50,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-60,10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-40,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(10,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(20,-10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(30,-20)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

def lightpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(-100,40)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    for times in range(4):
        a.left(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance)
    a.left(90)
    a.forward(distance*4)
    a.left(90)
    a.forward(distance*4)
    a.left(90)
    a.forward(distance*5)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance*2)
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-20,-70)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*4)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance*3)
    a.end_fill()

    a.penup()
    a.goto(-100,-90)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(40,-30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(30,-30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(20,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance*2)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(0,40)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-30,40)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-80,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def white(distance,color):
    a.color(color)
    a.penup()
    a.goto(-30,30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-40,30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(0,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(10,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-10,10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-50,10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-80,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def blue(distance,color):
    a.color(color)
    a.penup()
    a.goto(-70,10)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance*2)
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-60,40)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-30,40)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-10,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(10,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

def darkblue(distance,color):
    a.color(color)
    a.penup()
    a.goto(20,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(0,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-40,30)
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-70,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.hideturtle()
