#function file
import turtle
a=turtle.Turtle()

def light(distance,color):
    a.penup()
    a.goto(-130,30)
    a.pendown()
    a.color(color)
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

def dark(distance,color):
    a.color(color)
    a.begin_fill()
    a.penup()
    a.goto(-140,40)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()
    a.begin_fill()
    a.penup()
    a.goto(-150,60)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-160,80)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-140,90)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-130,70)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-210,70)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.end_fill()

def black(distance,color):
    a.penup()
    a.goto(-150,0)
    a.pendown()
    a.color(color)
    a.begin_fill()
    for times in range(2):
        a.right(90)
        a.forward(distance*3)
        a.right(90)
        a.forward(distance)
    a.left(180) 
    a.end_fill()

    a.penup()
    a.goto(-140,-10)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,-20)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*4)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-110,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-120,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-90)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-140,-90)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.right(90)
        a.forward(distance*2)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-130,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*8)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(-50,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-30,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*8)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(50,-110)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-90)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(30,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(50,-60)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(40,-20)
    a.pendown()
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*4)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(20,20)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(20,30)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*6)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*4)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-100,50)
    a.pendown()
    a.begin_fill()
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-160,70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-180,60)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
    a.end_fill()

def darkR (distance,color):
    a.color(color)
    a.penup()
    a.goto(-90,40)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-110,30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-140,20)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-150,30)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-160,50)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()
    
    a.penup()
    a.goto(-150,80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-180,70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-220,70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(-110,50)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-120,70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-110)
    a.pendown()
    a.begin_fill()
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.penup()
    a.goto(-30,-110)
    a.pendown()
    a.begin_fill()
    a.forward(distance*3)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(30,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(40,-70)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-60)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(50,-30)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.right(90)
        a.forward(distance)
    a.end_fill()



def darkpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(30,-110)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance*3)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(10,-80)
    a.pendown()
    a.begin_fill()
    for times in range(4):
        a.left(90)
        a.forward(distance)
    a.end_fill()

    a.penup()
    a.goto(-60,-110)
    a.pendown()
    a.begin_fill()
    a.right(90)
    a.forward(distance*6)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance*5)
    a.left(90)
    a.forward(distance*2)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-110,-80)
    a.pendown()
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-110,-40)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-120,-10)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-130,0)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-140,20)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-80,40)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-60,50)
    a.pendown()
    for times in range(2):
        a.forward(distance)
        a.left(90)
        a.forward(distance*4)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-50,10)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-50,-10)
    a.pendown()
    for times in range(2):
        a.forward(distance*2)
        a.left(90)
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,10)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,-10)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(-20,-50)
    a.pendown()
    for times in range(4):
        a.forward(distance)
        a.left(90)
    a.end_fill()

    a.penup()
    a.goto(30,10)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.forward(distance*2)
        a.right(90)
        a.forward(distance)
        a.right(90)
    a.end_fill()

    a.penup()
    a.goto(20,-70)
    a.pendown()
    a.begin_fill()
    for times in range(2):
        a.left(90)
        a.forward(distance)
        a.left(90)
        a.forward(distance*2)
    a.end_fill()
    
def medpink(distance,color):
    a.color(color)
    a.penup()
    a.goto(-120,-80)
    a.pendown()
    a.begin_fill()
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*5)
    a.left(90)
    a.forward(distance*2)
    a.left(90)
    a.forward(distance*3)
    a.left(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.right(90)
    a.forward(distance)
    a.left(90)
    a.forward(distance*2)
    a.end_fill()

    a.begin_fill()
    a.penup()
    a.goto(40,-80)
    for times in range(2):
        a.forward(distance*3)
        a.left(90)
        a.forward(distance*2)
        a.left(90)
    a.end_fill()
